### ISSUE TITLE
Issues with closed sockets

### ISSUE THREAD

**Issue by jwoertink** [cable-cr/cable#12]
When we go to send a message to a channel, we never account for if a socket is closed:

https://github.com/cable-cr/cable/blob/731d907fec20269c468d072d8cbfeabab6cfa374/src/cable/server.cr#L81-L86

What seems to happen is this call raises that `IO::Error`, but if you're using multiple channels, then any in that array never get called after the exception is raised.

We noticed this because we had both a `ChatChannel` and an `EventChannel` on the same page, and if a user was in middle of chatting and then killed their tab/browser, then everyone's chat would stop working. We didn't see the issue if it was just the `ChatChannel`. 

We came up with a fix that seems to work. I'm not sure if this is the best way to handle it or not.

```diff
- def send_to_channels(channel, message)
+ def send_to_channels(identifier, message)
     parsed_message = JSON.parse(message)

-   @channels[channel].each do |channel|
+   @channels[identifier].each do |channel|
+     if channel.connection.socket.closed?
+       @channels[identifier].delete(channel)
+     else
         Cable::Logger.info "#{channel.class} transmitting #{parsed_message} (via streamed from #{channel.stream_identifier})"
         channel.connection.socket.send({
            identifier: channel.identifier,
            message:    parsed_message,
         }.to_json)
+      end
     end
   end
```

**Comment by fernandes** [comment]
@jwoertink uowwww... that's a critical thing! I don't see why this couldn't be a good option, question: "any idea how to test it?" hahahhaha it seems _almost_  impossible to me 😬 for a connection to raise `IO::Error` but we can go move forward with this solution for sure

**Comment by jwoertink** [comment]
Testing may be a little tricky, but basically you would just need to create the socket, then close it before sending to the channel, and test that the channel no longer exists in `@channels`. I think WebSocket has a "close" method you could even call...

Looking at the code, you may need a way to access `@channels` unless you're ok with calling `Cable.server.@channels` 😬

**Comment by fernandes** [comment]
I was checking the tests, and there's none with two clients interacting at the same time, maybe we'd need to create two fibers for the clients, and somehow "control" them (sending messages to a channel), and after all stop? Or do you have a better (aka simpler) idea? 😄

**Comment by jwoertink** [comment]
I was thinking about this. I'm not sure how you could handle it. It seems it would be pretty complex in any case 😞  I haven't worked with the channels or fibers outside of what I've looked at in this shard 😅

**Comment by confact** [comment]
@jwoertink @fernandes you could push the fix out so the fix is there at least and try to figure out how to test it later? Maybe not the best way to do it but need to get those fixes out :D

**Comment by jwoertink** [comment]
Yeah, we're using this code in our app which has been good. It's at least a start.

**Comment by fernandes** [comment]
@jwoertink I left a `TODO` on the code, maybe we can revisit in the future.. thanks for bringing the issues and its solution 🍻

**Comment by jwoertink** [comment]
Sounds good! If I come up with an idea, I'll submit a PR for it. Thanks for adding that in!
