### ISSUE TITLE
handling unsubscribing from an channel

### ISSUE THREAD

**Issue by confact** [cable-cr/cable#15]
We have handled subscribing to a channel on connection but not on unsubscribing. We should probably add that?

**Comment by fernandes** [comment]
I tried to fix the tests on the PR, and I figured out whats happening, logger is duplicating the messages still need to figure out why

and about this feature, actioncable subscribe and sends the confirmation for subscription, or it's rejected and send confirmation for rejection, I couldn't find the `unsubscribe` thing, can you please point me in the rails docs or source where we have this unsubscription thing?

**Comment by fernandes** [comment]
I managed to fix the spec, it was related to sending messages to a non-open channel, I'm just unsure about this feature, how it should work

**Comment by fernandes** [comment]
I pushed to this [branch](https://github.com/cable-cr/cable/commits/unsubscribe) (I rebased with master) and fixed the specs on https://github.com/cable-cr/cable/commit/67f6eb2a06e9cee9d259345d08da0885d9c2557e

**Comment by confact** [comment]
@fernandes this is important for subscriptiont to remove the channel server-side if it unsubscribe.

@fernandes the front-end side is calling this on turbo when changing pages where the stream is set:
```
{"command":"unsubscribe","identifier":"{\"channel\":\"Turbo::StreamsChannel\",\"signed_stream_name\":\"fgfdgfdhfdhfdhfdfhfdhdf\"}"}
```

ActionCable to have a unsubscribe flow as well on front-end here:
https://github.com/rails/rails/blob/3eb546e75e2cf8d4ae26be90ae39765d49eeaddd/actioncable/app/javascript/action_cable/subscriptions.js#L36

Which is calling this: https://github.com/rails/rails/blob/3eb546e75e2cf8d4ae26be90ae39765d49eeaddd/actioncable/lib/action_cable/subscription_adapter/inline.rb#L19

Now we are just adding the channels to subscribe to but have no way to remove them, which we should be able to.

**Comment by fernandes** [comment]
@confact thanks for clarifying, I couldn't find yesterday this `unsubscribe` command, but you are totally right we need to fix it
