### ISSUE TITLE
Reject an subscription to an channel

### ISSUE THREAD

**Issue by confact** [cable-cr/cable#17]
Every user should not have access to every channel. Check and reject if they are not authorized.

ActionCable on ruby has the reject method:
https://github.com/rails/rails/blob/5aaaa1630ae9a71b3c3ecc4dc46074d678c08d67/actioncable/lib/action_cable/channel/base.rb#L240

**Comment by fernandes** [comment]
We have the `reject_unauthorized_connection`, maybe we should rename to follow rails convention?

If you wanna see it working, you can check the [spec](https://github.com/cable-cr/cable/blob/c8a9a2b9cc78963b6a031d6e6238ba955f4fa146/spec/cable/connection_spec.cr#L325) where we test it

**Comment by confact** [comment]
@fernandes that's for the connection. The connection should work but the user should not be able to subscribe to every channel to listen to updates. We need some safeguards there. The reject button I was linking to is to only reject access to that channel. Not stop the whole connection.

**Comment by fernandes** [comment]
yeah! I looked on the channel docs, and now I see what you mean here https://github.com/rails/rails/blob/5aaaa1630ae9a71b3c3ecc4dc46074d678c08d67/actioncable/lib/action_cable/channel/base.rb#L81-L91

we need to handle it for sure! thanks

**Comment by confact** [comment]
@fernandes good! I would need that as I support both guest and user and analytics data is sensitive. 

If I have time I can look into it but not sure. So if you are faster than me I would be happy :D

**Comment by fernandes** [comment]
@confact please check the PR 😉
