### ISSUE TITLE
undefined local variable or method 'payload' for ApplicationCable::Connection

### ISSUE THREAD

**Issue by jwoertink** [cable-cr/cable#4]
In the README it says we can use `self.identifier = payload["id"].to_s`, but this throws the undefined error.

**Comment by fernandes** [comment]
ohhhh you're right, it's supposed to be:

```crystal
# Implement your Auth logic, something like
payload = JWT.decode(token, Lucky::Server.settings.secret_key_base, JWT::Algorithm::HS256)
self.identifier = payload["id"].to_s
self.current_user = UserQuery.find(payload["id"])
```

so `payload` is the return of `JWT.decode` and we need to use `token` (the one was passed on the URL)
