### ISSUE TITLE
Why do we send a message that says ping instead of a ping?

### ISSUE THREAD

**Issue by jwoertink** [cable-cr/cable#64]
https://github.com/cable-cr/cable/blob/e725d9e4c5f638a7d26092256377aa8ad618a173/src/cable/websocket_pinger.cr#L29

instead of `@socket.ping(Time.utc.to_unix.to_s)`?

@mjeffrey18 would you happen to know?

**Comment by fernandes** [comment]
@jwoertink mostly to keep the same as rails ~ping~ [beat](https://github.com/rails/rails/blob/bd8aeead92c11dbd82ddb9f114ea63b0daf160b4/actioncable/lib/action_cable/connection/base.rb#L135) command
