### ISSUE TITLE
Create a Crystal client for Cable

### ISSUE THREAD

**Issue by jwoertink** [cable-cr/cable#65]
I came across this sweet gem https://github.com/NullVoxPopuli/action_cable_client

It works really well, and makes connecting to a cable server from another server-side really easy. I'd like to make one for us.

@fernandes I don't have access beyond this repo, would you mind making a new repo maybe called `cable-client` and get me access?

**Comment by fernandes** [comment]
@jwoertink hey my friend, I just added you to the organization, that's well deserved, thank you for everything 🙇

**Comment by jwoertink** [comment]
This isn't "done", but this issue can be closed now that we have the repo started at https://github.com/cable-cr/cable-client
