### ISSUE TITLE
Accounting for bad data

### ISSUE THREAD

**Issue by jwoertink** [cable-cr/cable#67]
We have several spots where we assume the JSON coming over the wire is valid like 

https://github.com/cable-cr/cable/blob/fb45456e4c4a4dc55fdf495d131f3aeb2089d359/src/cable/payload.cr#L15

https://github.com/cable-cr/cable/blob/fb45456e4c4a4dc55fdf495d131f3aeb2089d359/src/cable/payload.cr#L30

https://github.com/cable-cr/cable/blob/fb45456e4c4a4dc55fdf495d131f3aeb2089d359/src/cable/payload.cr#L38

but `JSON.parse("")` is perfectly valid, but doesn't really make sense in these spots... I'm not sure of what all the edge cases are, but at least catching bad JSON is a good first start

**Comment by jwoertink** [comment]
Ok, so after booting up a sample rails app and blasting it with bad data, it turns out that rails doesn't handle it well...

```
15:37:06 web.1  | Received unrecognized command in {"command"=>"messagge", "identifier"=>"{\"channel\":\"RoomChannel\",\"room_id\":1}", "data"=>"{\"action\":\"speak\",\"message\":\"bacon\"}"}
```

Rails basically just borks, and never sends back any sort of error message, but still somehow allows the client to stay alive.  That just seems wrong to me, but I guess that is what it is??

**Comment by jwoertink** [comment]
Just for reference, I booted up https://github.com/okeeffed/demo-action-cable-hello-world and https://blog.dennisokeeffe.com/blog/2022-02-28-action-cable-hello-world-with-rails-7

**Comment by wout** [comment]
I have used Cable.cr superficially, so I can't speak from experience. What you're proposing looks great. It's how I would approach it anyway.

**Comment by fernandes** [comment]
we could set a class to serialize at channel level, not at connection level, connection will receive messages from ALL the channels, hard (and useless?) to have a class to handle all the cases

on the channel level seems more interesting/reliable, the connection could get the serializer from the class and parse, if doesn't work return an error, the idea is to keep it 100% with actioncable.js, if the JS doesn't play well with an error message, then I'd say to just ignore it

thoughts?
